### ISSUE TITLE
fs.errors.CreateFailed: could not get an IP for name

### ISSUE THREAD

**Issue by tkossak** [althonos/fs.smbfs#2] opened 2018-04-12 14:42 UTC
Hi, I get following error while creating SMBFS object with host name:

```
  File "/home/kossak/Kossak/files_common/PythonProjects/testowy/testowy/test_pyfilesystem.py", line 43, in test_smb
    f = SMBFS(host=host, username=user, passwd=password)
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/fs/smbfs/smbfs.py", line 224, in __init__
    "could not get an IP for name: '{}'".format(host))
fs.errors.CreateFailed: could not get an IP for name: '<HOST>'
```

and with IP address:

```
  File "/home/kossak/Kossak/files_common/PythonProjects/testowy/testowy/test_pyfilesystem.py", line 44, in test_smb
    f = SMBFS(host=host, username=user, passwd=password)
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/fs/smbfs/smbfs.py", line 214, in __init__
    "could not get a name for IP: '{}'".format(host))
fs.errors.CreateFailed: could not get a name for IP: '<IP>'
```

I can connect to `smb://<HOST>/` with my file manager without any errors. I can also ping it (by name and IP) and it responds properly. Any idea why it doesn't work with SMBFS? Thank you in advance.

I use:
Python: 3.6.2
fs.smbfs.__ version__: 0.3.3
os: Linux Mint

**Comment by althonos** [comment] 2018-04-12 15:53
Hi @tkossak,

`SMBFS` relies on the NetBIOS naming service to query the name from the IP, or the IP from the name. It could be that the NetBIOS service is not running on your server, or that it's running in a non-standard port (which is supposed to be `137`)

You could check if its with the following snippet:
```python
import nmb.NetBIOS
nb = nmb.NetBIOS.NetBIOS()
response = nb.queryIPForName("<IP>")  # with you IP here obviously
print(nb)
```

I have to figure out a non-stupid way to allow passing directly both the hostname and the IP, since in cases like yours you already know both and don't need to use NetBIOS.

**Comment by tkossak** [comment] 2018-04-13 11:05
> import nmb.NetBIOS
> nb = nmb.NetBIOS.NetBIOS()
> response = nb.queryIPForName("<IP>")  # with you IP here obviously
> print(nb)

This returns None for me. Can we use stdlib to get IP?:

```python
import socket
socket.gethostbyname('<HOSTNAME>')
```
(this works for me, in contrast to NetBIOS)

> I have to figure out a non-stupid way to allow passing directly both the hostname and the IP,

Maybe we can past `host` parameter either as string (host or IP) or as tuple `('host', 'ip')` in 
https://github.com/althonos/fs.smbfs/blob/master/fs/smbfs/smbfs.py#L203 ?

**Comment by althonos** [comment] 2018-04-13 15:26
Hi @tkossak,

> Can we use stdlib to get IP/HOST?:
Unfortunately not, since the SMB host name may not be the same as the network hostname.

> Maybe we can past host parameter either as string (host or IP) or as tuple ('host', 'ip') 
I added a patch for this in the `fix-2` branch: you can try it after installing with

```
pip install --user https://github.com/althonos/fs.smbfs/archive/fix-2.zip
```

and then use with:
```python
import fs.smbfs
my_fs = fs.smbfs.SMBFS(("<HOSTNAME>", "<IP>"), ...)
```

If it works well, I'll merge in master and publish a new release.

**Comment by tkossak** [comment] 2018-04-16 13:16
I executed `f = SMBFS(host=(host, ip), username=user, passwd=password)` and it gave me this error:
```
Traceback (most recent call last):
  File "/home/kossak/apps/pycharm-community/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/kossak/apps/pycharm-community/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/kossak/apps/pycharm-community/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/kossak/apps/pycharm-community/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/kossak/Kossak/files_common/PythonProjects/testowy/testowy/test_pyfilesystem.py", line 52, in <module>
    test_smb()
  File "/home/kossak/Kossak/files_common/PythonProjects/testowy/testowy/test_pyfilesystem.py", line 45, in test_smb
    f = SMBFS(host=(host, ip), username=user, passwd=password)
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/fs/smbfs/smbfs.py", line 235, in __init__
    share.name for share in self._smb.listShares()
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/smb/SMBConnection.py", line 149, in listShares
    self._pollForNetBIOSPacket(timeout)
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/smb/SMBConnection.py", line 614, in _pollForNetBIOSPacket
    self.feedData(data)
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/nmb/base.py", line 54, in feedData
    self._processNMBSessionPacket(self.data_nmb)
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/nmb/base.py", line 75, in _processNMBSessionPacket
    self.onNMBSessionMessage(packet.flags, packet.data)
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/smb/base.py", line 138, in onNMBSessionMessage
    if self._updateState(self.smb_message):
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/smb/base.py", line 279, in _updateState_SMB2
    req.callback(message, **req.kwargs)
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/smb/base.py", line 505, in readCB
    decodeResults(read_message.tid, kwargs['fid'], kwargs['data_bytes'] + data_bytes[24:data_len-24])
  File "/home/kossak/.virtualenvs/testowy-jc7bDP4y/lib/python3.6/site-packages/smb/base.py", line 476, in decodeResults
    max_length, _, length = struct.unpack('<III', data_bytes[offset:offset+12])
struct.error: unpack requires a bytes object of length 12
```

**Comment by althonos** [comment] 2018-05-02 08:58
Ah, it looks the underlying NetBIOS calls are not working either. It might help to try with `direct_tcp` set to `True` when creating the `SMBFS` (hopefully).

**Comment by dcalde** [comment] 2018-06-29 03:30
This works for me:
```
        if utils.is_ip(host) or host == 'localhost':
            self._server_ip = ip = host
            self._server_name = host
            direct_tcp = True
```
I will do more testing, but so far so go.

**Comment by mivade** [comment] 2019-05-17 21:15
I'm getting bit by this issue, too. I'm not too familiar with how SMB works internally, but why is NetBIOS needed at all? I have SMB shares mounted on a Linux server with entries like `//fqdn/share` but trying to use either the FQDN or IP address fails with this package.

**Comment by exislow** [comment] 2020-03-10 13:30
I have the same problem on macOS 10.15 Catalina. Any solutions for this?
`netbios.queryIPForName('<ip>')` returns None.

**Comment by mivade** [comment] 2020-04-14 15:45
@althonos I'm not entirely sure why PR #7 should close this issue. I'm still unable to connect to a Windows share from a Linux cluster. I've tried connecting in a variety of ways including the new one added in #7 but nothing seems to work.

**Comment by althonos** [comment] 2020-04-14 17:49
@mivade : i guess passing an IP + a hostname was a fix for some people, but if you still have this issue i'm gonna keep it open then.

**Comment by telamonian** [comment] 2020-04-15 20:48
@exislow The problem on OSX is that OSX runs it's own netbios server as `netbiosd`, which loads on startup by default. Apparently `netbiosd` ends up sucking up all traffic to ports 137 and 138. If you're trying to ping a different netbios server, you can either make sure that server is listening on some different port (say, 3669), or you can shut down `netbiosd`.

I was able to (temporarily) fix a similar issue to yours by unloading/shutting down `netbiosd`:

```
sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.netbiosd.plist
```

Not sure what stopping `netbiosd` breaks, but it probably breaks something (native file sharing on OSX?), so you should probably then reload it at some point:

```
sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.netbiosd.plist
```

**Comment by mivade** [comment] 2020-04-15 21:08
My main pain point is that (AFAIK) I *have* no netbios service running on Linux. Unfortunately I can't seem to quite figure out why the connection always fails even if I know the IP address (which `socket.gethostbyname` can resolve for me just fine).

**Comment by telamonian** [comment] 2020-04-17 00:38
@mivade fs.smbfs is built on top of pysmb, which provides a low-level api in Python for interacting with Samba. pysmb provides the `smb` package, which is what actually does all of the heavy lifting in terms of communicating with your smb server. In order to debug your issue, try connecting to your smb server using just the `smb` package by running this code:

```
from smb.SMBConnection import SMBConnection

conn = SMBConnection(<smb-username>, <smb-password>, '', <smb-host-fqdn>)
conn.connect(<smb-host-ip>)

print([s.name for s in conn.listShares()])
```

- If the names of all the shares on your server get printed out, that means that your server is configured correctly and pysmb is working as intended. That would mean you are indeed running into a bug in fs.smbfs

- If the above code instead produces some error, then either your server is misconfigured or you've run into a bug in pysmb

**Comment by mivade** [comment] 2020-04-17 15:19
Here's what I see:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    conn.connect(ip)
  File "/home/mdepalatis/shared/miniconda3/envs/pyfs/lib/python3.8/site-packages/smb/SMBConnection.py", line 122, in connect
    self._pollForNetBIOSPacket(timeout)
  File "/home/mdepalatis/shared/miniconda3/envs/pyfs/lib/python3.8/site-packages/smb/SMBConnection.py", line 594, in _pollForNetBIOSPacket
    raise NotConnectedError
smb.base.NotConnectedError
```

So my question is this: Why is a NetBIOS server even required in the first place? As I mentioned earlier I am fairly certain that my Linux cluster doesn't have this service running but does have `smbclient` and associated tools installed. I have managed to get transfers working using `smbclient` directly, so I have a workaround, albeit a rather awkward one. For now I can check for a related issue in the `smb` package and move the discussion over there.

**Comment by mivade** [comment] 2020-04-20 21:27
Following discussion in https://github.com/miketeo/pysmb/issues/156 it looks like the issue was that the FQDN is *not* what needs to be given in the host. I was able to get things working using a `(ip, short_hostname)` tuple. It would be helpful to give some more details on this in the README (I will make a PR shortly to address this). @althonos from my perspective you can close this issue again.

**Closed** 2020-04-21 13:16 UTC
Labels: bug

**Comment by dntq83** [comment] 2020-08-03 05:09
@tkossak I have same issued 
`smbServer = smbfs.SMBFS((serverHost, "192.168.0.3"), username="xxxx", passwd="xxxxx", timeout=30)
  File "/usr/local/lib/python3.6/dist-packages/fs/smbfs/smbfs.py", line 235, in __init__
    self._smb.connect(self._server_ip, **connect_kw)
  File "/usr/local/lib/python3.6/dist-packages/smb/SMBConnection.py", line 122, in connect
    self._pollForNetBIOSPacket(timeout)
  File "/usr/local/lib/python3.6/dist-packages/smb/SMBConnection.py", line 596, in _pollForNetBIOSPacket
    raise NotConnectedError
smb.base.NotConnectedError`
I can connect via mount.cifs and ping to host.
Could you show me how can I fix that problem?

Thank you!

System Information:
Ubuntu 18.04
fs.smbfs version 0.6.3
